### ISSUE TITLE
get skype name

### ISSUE THREAD

**Issue by sfm2222** [Azure-Samples/active-directory-dotnet-desktop-msgraph-v2#11]
Through what permission I can get skype name from the graph API. I can log in into Microsoft account but unable to fetch skype name along with profile data.

I just want to login into my windows form application using Microsoft account and get skype username.

**Comment by sfm2222** [comment]
@jmprieur could you please check how can I obtain skype name from graph API in response after login.

**Comment by sfm2222** [comment]
@jmprieur  thank you for your reply. If you can clear that how can I login into Skype account from windows form application that would be great. I am unable to find anything related to it in the documentation.

**Comment by asymonds1129** [comment]
I  do not want Github. I do not know what it is. I just want my skype account back the way it always was please.

**Comment by asymonds1129** [comment]
Github came up automatically in my skype account access page, preventing access to Skype, it looked like some new thing one had to do before getting into Skype. I checked on line what and who Github is.  Net result was that I have had to reinstall skype.  It took me well over an hour to get back on skype. I presume I am not the only person with the problem
Sent from Yahoo Mail on Android 
 
  On Mon, 26 Aug 2019 at 19:33, Hirsch Singhal<notifications@github.com> wrote:   
@asymonds1129 - If your skype account has been impacted in some way by using GitHub, please let me know by replying here. Otherwise, you can continue using your Skype account by typing in your Skype username into any username field, and then choosing to use your password by selecting "Other ways to sign in" and picking "Use my password"

**Comment by jmprieur** [comment]
Closing the issue (which is not about the sample). @hpsin is following-up offline
